[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports_ignore = ["test", "script"]

solc = "0.8.24"
optimizer = true
optimizer_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
